#!/usr/bin/env python3

import gi
import os
import signal
import time
import subprocess

gi.require_versions({
    'Gtk': '3.0',
    'Gst': '1.0',
    'AppIndicator3': '0.1',
    'Notify': '0.7',
    'GLib': '2.0'
})

from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
from gi.repository import Notify as notify
from gi.repository import GLib

APPINDICATOR_ID = 'openvpn3-applet'
ICON_PATH = os.path.dirname(os.fspath("/usr/share/icons/hicolor/scalable/apps/"))
CONNECTED_ICON = "/nm-vpn-active-lock-symbolic.svg"
DISCONNECTED_ICON = "/nm-vpn-connecting01-symbolic.svg"
OVPN_CONFIG = os.environ.get('OVPN_CONFIG')

class Indicator():
    def __init__(self):
        self.indicator = appindicator.Indicator.new(APPINDICATOR_ID, \
                ICON_PATH+DISCONNECTED_ICON, \
                appindicator.IndicatorCategory.APPLICATION_STATUS)
        self.indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
        self.indicator.set_menu(self.build_menu())
        notify.init("sessionInfo")
        self.update_icon()

    def update_icon(self):
        # check if a session is active using `openvpn3 sessions-list`
        session_list = os.popen("openvpn3 sessions-list").read()
        if "Status: Connection, Client connected" in session_list:
            self.indicator.set_icon_full(ICON_PATH+CONNECTED_ICON, "Connected")
            # schedule the next update in 5 seconds
            GLib.timeout_add_seconds(5, self.update_icon)
        else:
            self.indicator.set_icon_full(ICON_PATH+DISCONNECTED_ICON, "Disconnected")
        return False

    def build_menu(self):
        menu = gtk.Menu()

        command_one = gtk.MenuItem(label='Connect')    
        command_one.connect('activate', self.connect) 
        menu.append(command_one)                 
                                                 
        command_two = gtk.MenuItem(label='Disconnect') 
        command_two.connect('activate', self.disconnect)
        menu.append(command_two)                 
                                                 
        command_three = gtk.MenuItem(label='Kill Switch')
        command_three.connect('activate', self.kill)
        menu.append(command_three)

        command_four = gtk.MenuItem(label='Current Sessions')
        command_four.connect('activate', self.list)
        menu.append(command_four)
        
        exittray = gtk.MenuItem(label='Exit Tray')
        exittray.connect('activate', self.quit)
        menu.append(exittray)

        menu.show_all()
        return menu

    def connect(self, source):
        # check if a session is already active
        session_list = os.popen("openvpn3 sessions-list").read()
        if "Status: Connection, Client connected" in session_list:
            notifyActiveSession = notify.Notification.new("A session is already active.")
            notifyActiveSession.set_urgency(1)
            notifyActiveSession.show()
            return
        
        # initiate a new session
        sessionStart = os.popen("openvpn3 session-start --config {0}".format(OVPN_CONFIG)).read()
        notifySessionStart = notify.Notification.new(sessionStart)
        notifySessionStart.set_urgency(1)
        notifySessionStart.show()

        # monitor the session start
        for _ in range(6):  # try 6 times
            time.sleep(5)   # spaced five seconds apart
            session_list = os.popen("openvpn3 sessions-list").read()
            if "Status: Connection, Client connected" in session_list:
                self.update_icon()
                return True
            elif "No sessions available" in session_list:
                self.indicator.set_icon_full(ICON_PATH+DISCONNECTED_ICON, "Disconnected")
                notifySessionError = notify.Notification.new("Connection failed.")
                notifySessionError.set_urgency(1)
                notifySessionError.show()
                return False

    def disconnect(self, source):
        sessionStop = os.popen("openvpn3 session-manage --disconnect --config {0}".format(OVPN_CONFIG)).read()
        notifySessionStop = notify.Notification.new(sessionStop)
        notifySessionStop.set_urgency(1)
        notifySessionStop.show()
        
    def kill(self, source):
        self.disconnect(source)
        sessionsKill = os.popen("sudo kill -9 $(ps aux | grep openvpn3-service* | awk '{print $2}')")
        notifySessionsKill = notify.Notification.new(sessionsKill)
        notifySessionsKill.set_urgency(1)
        notifySessionsKill.show()
        
    def list(self, source):
        sessionsList = os.popen("openvpn3 sessions-list").read()
        notifySessionsList = notify.Notification.new(sessionsList)
        notifySessionsList.set_urgency(1)             
        notifySessionsList.show()

    def quit(self, source):
        session_list = os.popen("openvpn3 sessions-list").read()
        if "Status: Connection, Client connected" in session_list:
            self.disconnect(None)
            gtk.main_quit()
        else:
            gtk.main_quit()

Indicator()
signal.signal(signal.SIGINT, signal.SIG_DFL)
gtk.main()
