#!/bin/bash
 
set -eu
OVPN_CONFIG=""
 
usage() {
    cat << EOF
Usage: $0 [-c|-d|-l|-h]
 
list / connect / disconect OpenVPN session.
 
-l list current sessions
-c connect
-d disconect
-h help
 
EOF
    exit 0
}
 
connect() {
	notify-send \
			-u low \
			-i /usr/share/icons/hicolor/scalable/apps/nm-vpn-standalone-lock-symbolic.svg \
			"Connecting to Sonatype VPN"
    openvpn3 session-start --config $OVPN_CONFIG
}

disconnect() {
	notify-send \
			-u low \
			-i /usr/share/icons/hicolor/scalable/apps/nm-vpn-standalone-lock-symbolic.svg \
			"Disconnecting from Sonatype VPN"
    openvpn3 session-manage --disconnect --config $OVPN_CONFIG
}
 
list() {
    openvpn3 sessions-list
}
 
ACTION="list"
while getopts cdlh arg; do
    case "$arg" in
        c) ACTION="connect" ;;
        d) ACTION="disconnect" ;;
        l) ACTION="list" ;;
        h) usage ;;
    esac
done
 
case $ACTION in
    connect)
        connect
        ;;
    disconnect)
        disconnect
        ;;
    list)
        list
        ;;
    usage)
        usage
        ;;
    *)
        echo "unrecognized action: $ACTION" >&2
        exit 1
        ;;
esac
